#!/usr/bin/env bash
set -euo pipefail
URL_JSON=$(node -p 'JSON.stringify(process.argv[1])' "${1:-http://127.0.0.1:5173}")

ego-browser nodejs <<JS
const url = $URL_JSON
await useOrCreateTaskSpace('BotWorkspace interaction regression')
await openOrReuseTab(url, {wait: true, timeout: 30})
await gotoAndWait(url, {timeout: 30, settle: 0.2})
// Account for an inherited browser zoom without changing the user's profile setting.
async function viewport(width, height) {
  const metrics = {width, height, deviceScaleFactor:1, mobile:false}
  await cdp('Emulation.setDeviceMetricsOverride', metrics)
  await wait(1)
  const ratio = width / (await pageInfo()).w
  await cdp('Emulation.setDeviceMetricsOverride', {...metrics, width:Math.round(width * ratio), height:Math.round(height * ratio)})
  await wait(1)
  if ((await pageInfo()).w !== width) throw new Error('Viewport did not settle to requested CSS width')
}
await viewport(1440, 900)
const check = (condition, label) => { if (!condition) throw new Error(label); cliLog('PASS ' + label) }
check(await js("document.querySelector('h1')?.textContent") === 'Studio notes', 'initial conversation')
check(await js("document.querySelector('.send-button')?.disabled"), 'empty compose disabled')
await js("[...document.querySelectorAll('.space-row')].find(x=>x.textContent.includes('Signal garden')).click()")
await wait(0.2)
check(await js("document.querySelector('h1')?.textContent") === 'Signal garden', 'space selection')
await fillInput('textarea', 'Regression note — stays in this browser.')
await click('.send-button', {label: 'add regression note'})
await wait(0.2)
check(await js("[...document.querySelectorAll('.message-content p')].some(x=>x.textContent==='Regression note — stays in this browser.')"), 'local message added')
check(await js("document.querySelector('textarea').value") === '', 'composer cleared')
check(await js("document.querySelector('.space-row.is-active .space-count').textContent") === '3', 'message count uses real records')
await fillInput('textarea', 'Keyboard note')
await js("document.querySelector('textarea').dispatchEvent(new KeyboardEvent('keydown', {key:'Enter', code:'Enter', bubbles:true, isComposing:true}))")
await wait(0.2)
check(await js("document.querySelector('textarea').value") === 'Keyboard note', 'IME Enter does not submit')
await cdp('Input.dispatchKeyEvent', {type:'keyDown', key:'Enter', code:'Enter', windowsVirtualKeyCode:13, modifiers:8, text:'\r'})
await cdp('Input.dispatchKeyEvent', {type:'keyUp', key:'Enter', code:'Enter', windowsVirtualKeyCode:13, modifiers:8})
await wait(0.2)
check(await js("document.querySelector('textarea').value.includes(String.fromCharCode(10))"), 'Shift Enter inserts newline')
await cdp('Input.dispatchKeyEvent', {type:'keyDown', key:'Enter', code:'Enter', windowsVirtualKeyCode:13, text:'\r'})
await cdp('Input.dispatchKeyEvent', {type:'keyUp', key:'Enter', code:'Enter', windowsVirtualKeyCode:13})
await wait(0.2)
check(await js("document.querySelector('textarea').value") === '', 'Enter adds message')
check(await js("document.querySelectorAll('.message-tag.local').length") === 2, 'only local messages receive badges')
check(await js("document.querySelector('.detail-list div:last-child dd').textContent") === '3', 'participant count uses real authors')
await js("[...document.querySelectorAll('.space-row')].find(x=>x.textContent.includes('Studio notes')).click()")
await wait(0.2)
check(!await js("[...document.querySelectorAll('.message-content p')].some(x=>x.textContent.startsWith('Regression note'))"), 'space messages isolated')
await js("[...document.querySelectorAll('.space-row')].find(x=>x.textContent.includes('Signal garden')).click()")
await wait(0.2)
check(await js("[...document.querySelectorAll('.message-content p')].some(x=>x.textContent.startsWith('Regression note'))"), 'local state retained across selection')
await fillInput('input[type=search]', 'no-match-for-this-regression')
await wait(0.2)
check(await js("document.querySelectorAll('.space-row').length") === 0, 'empty search state')
await click('.empty-state button', {label: 'clear empty search'})
await wait(0.2)
check(await js("document.querySelectorAll('.space-row').length") === 3, 'search recovery')
await click('.theme-button', {label: 'switch visual theme'})
await wait(0.2)
check(await js("document.querySelector('.app-shell').classList.contains('soft-light')"), 'theme toggle')
await viewport(390, 844)
await wait(0.2)
await js("document.querySelector('.mobile-nav-button').click()")
await wait(0.2)
check(await js("document.querySelector('.spaces-panel').classList.contains('is-mobile-open')"), 'mobile spaces open')
check(await js("getComputedStyle(document.querySelector('.conversation-panel')).display") === 'none', 'mobile panel replaces rather than overlays conversation')
check(await js("document.activeElement.getAttribute('aria-label')") === 'Close spaces panel', 'panel opens with keyboard focus')
await js("document.querySelector('.spaces-panel .mobile-close').click()")
await wait(0.2)
check(!await js("document.querySelector('.spaces-panel').classList.contains('is-mobile-open')"), 'mobile spaces close')
check(await js("getComputedStyle(document.querySelector('.spaces-panel')).display") === 'none', 'closed mobile panel removed from tab order')
check(await js("document.activeElement.id") === 'toggle-spaces', 'focus returns to mobile trigger')
await js("document.getElementById('toggle-inspector').click()")
await wait(0.2)
check(await js("document.querySelector('.inspector-panel').classList.contains('is-mobile-open')"), 'mobile details opens')
await cdp('Input.dispatchKeyEvent', {type:'keyDown', key:'Escape', code:'Escape', windowsVirtualKeyCode:27})
await cdp('Input.dispatchKeyEvent', {type:'keyUp', key:'Escape', code:'Escape', windowsVirtualKeyCode:27})
await wait(0.2)
check(await js("getComputedStyle(document.querySelector('.inspector-panel')).display") === 'none', 'Escape closes panel')
check(await js("document.documentElement.scrollWidth <= innerWidth && document.documentElement.scrollHeight <= innerHeight + 1"), 'mobile shell has no page overflow')
cliLog('Interaction regression passed. Session-local behavior preserved.')
JS

ego-browser nodejs <<'JS'
cliLog(await completeTaskSpace('BotWorkspace interaction regression', {keep:false}))
JS
